spring:
  datasource:
    url: jdbc:h2:mem:document-collector;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
  flyway:
    locations: classpath:db/migration/common, classpath:db/migration/test